server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        # Ruta para usuario-service
        - id: usuario-service
          uri: lb://usuario-service
          predicates:
            - Path=/api/users/**

        # Ruta para simulacion-service
        - id: simulacion-service
          uri: lb://simulacion-service
          predicates:
            - Path=/api/simulations/**

        # Ruta para prestamo-service
        - id: prestamo-service
          uri: lb://prestamo-service
          predicates:
            - Path=/api/loans/**
